# Custom Language File for Launcher Customizer

[ejs.app]
title = "Shiba Box Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Shibetendo64/ShibaboxLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/MYw5BUmNSV"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalzi/HeliosLauncher/"
supportLink = "https://github.com/dscalzi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO SHIBABOX"
welcomeDescription = "Welcome to Shibabox.eu, where the spirit of adventure and exploration reigns supreme, transforming the Minecraft experience into an epic journey reminiscent of legendary tales. Set forth into a world teeming with mystery and wonder, where each corner holds the promise of discovery and adventure. Our modded Minecraft server offers a unique twist on gameplay, imbuing it with elements that evoke the essence of timeless legends. Traverse vast landscapes adorned with remnants of ancient civilizations, encounter mythical creatures shrouded in myth and mystery, and unravel the secrets of forgotten realms."
welcomeDescCTA = "You are just a few clicks away from adventure."
